const actions = {
    GET_TABLE_LIST_STARTED: "GET_TABLE_LIST_STARTED",
    GET_TABLE_LIST_SUCCESS: "GET_TABLE_LIST_SUCCESS",
    GET_TABLE_LIST_FAILURE: "GET_TABLE_LIST_FAILURE",
    SET_SIGNUP_EMAIL: "SET_SIGNUP_EMAIL",
    SET_SIGNUP_PASSWORD: "SET_SIGNUP_PASSWORD",
    SET_SIGNUP_CONFIRM_PASSWORD: "SET_SIGNUP_CONFIRM_PASSWORD",
    SET_SIGNUP_NAME: "SET_SIGNUP_NAME"
};

export default actions;