const actions = {
    GET_TABLE_LIST_STARTED: "GET_TABLE_LIST_STARTED",
    GET_TABLE_LIST_SUCCESS: "GET_TABLE_LIST_SUCCESS",
    GET_TABLE_LIST_FAILURE: "GET_TABLE_LIST_FAILURE",

    GET_SIGNIN_STARTED: "GET_SIGNIN_STARTED",
    GET_SIGNIN_SUCCESS: "GET_SIGNIN_SUCCESS",
    GET_SIGNIN_FAILURE: "GET_SIGNIN_FAILURE",

    SET_SIGNIN_EMAIL:"SET_SIGNIN_EMAIL",
    SET_SIGNIN_PASSWORD:"SET_SIGNIN_PASSWORD",
    SET_SIGNIN_ERROR:"SET_SIGNIN_ERROR",
};

export default actions;